### ISSUE TITLE
MIDI Renditions break every second

### ISSUE THREAD

**Issue by SoulRepo** [Difegue/DoujinSoft#1]
Play any record in chrome, and it stops every second and back again.

**Comment by Difegue** [comment]
I'll be looking this up now that I'm done with WC24 -- Likely an issue with my built-in version of [midiJS](https://www.midijs.net/) being too old.

**Comment by Difegue** [comment]
I quickly tested on Firefox and new-Edge (which is running Chromium under the hood) and didn't find any issue.  

This might be googlechrome-specific, but I find it weird they'd deviate from chromium on webaudio stuff; Maybe the instruments aren't all loading properly on your side?  

MIDI in the browser isn't a very pretty thing due to the size of the samples that have to be passed to the client; I thought there'd be a better option 2 years later that'd allow me to use the [DIY soundfont](https://musical-artifacts.com/artifacts/490), but it doesn't look bright.

**Comment by Difegue** [comment]
This is likely fixed now that the midi implementation under the hood has substantiallly changed -- Closing.
