### ISSUE TITLE
WarioWare D.I.Y. 100% clean "no cheat" fresh saves with injected micros alone that should be uploaded to doujinsoft.

### ISSUE THREAD

**Issue by ghost** [Difegue/DoujinSoft#23]
sure these micros themselves in these saves might already have been uploaded to this website, but still it would be very convenient to have a save containing these GameFaqs micros but first off 100% clean untouched no cheats at all while still containing these micros uploaded to this website, for Android, MacBook, and Linux users, as bobmcjr's injector is unsupported on phones and has issues on non windows computers.

[WarioWare D.I.Y. clean no cheats fresh micros saves - quick port from the GameFaqs D.I.Y. Showcase saves.zip](https://github.com/Difegue/DoujinSoft/files/9427005/WarioWare.D.I.Y.clean.no.cheats.fresh.micros.saves.-.quick.port.from.the.GameFaqs.D.I.Y.Showcase.saves.zip)

https://gamefaqs.gamespot.com/wii/959422-warioware-diy-showcase/saves

**Comment by Pkwamooo** [comment]
the DS and Wii built in micros are not downloadable/user-generated content (it was even established that there were no plans to add these built in micros to doujinsoft in a previous issue), so "WA4E--all Game Blender modes are available. Also, the D.I.Y. sections are filled with all of Mona, Jimmy T., Ashley, and Orbulon's products from the Nintendo DS counterpart." would be skipped
and "WA4E--all Game Blender modes are available. Also, the D.I.Y. sections are filled with games from the NinSoft Store from 3/29/10 to 5/03/10, as well as the 9-Volt, D.I.Y. 101, and Job Center products." would have the 9-Volt stuff from that save cut off (due to not being downloadable/user-generated content) with the bobmcjr inject tool to upload just the downloadable/user-generated user stuff save to doujinsoft.

**Comment by pjamwamooo** [comment]
almost forgot, use a clean untouched fresh save of DIY Showcase (both US and EU) as well and faithfully inject all those Micros, Music, and Comic to the GameFaqs saves to each clean save (Micros, Music, and Comic are listed faithful to the GameFaqs save but the save is completely clean untouched fresh save without any cheats, friends, survey box, and scores), as the actual GameFaqs saves are otherwise cheating, and cheating (in both versions, especially the DS version) makes it rather boring very quickly.

**Comment by pkamwamooo** [comment]
almost forgot, fyi when a micro is injected in slot 1 in a empty ds save file, after the mona sampling then forced to make a micro "warioquest" in the tutorial after the take job part no matter if yes or no, it overwrites the injected first slot micro regardless, so had to make a backup inject to inject the first micro at slot 90 so it would still remain there, after that first micro you make if save is started then swap slot 1 with slot 90 to feel closer to the medly of diy games from each respective showcase save.

**Comment by pkamwamo** [comment]
the comment made a day earlier than this is just a disclaimer, and should only be on the .txt notes. warning, don't put any cheat saves on doujinsoft like ever.

**Comment by pksylvain0** [comment]
it's best when the save (while still containing the DLC/Showcase microgames from the zip download link for DS above) is 100% clean and nearly untouched for both DS and Wii versions. (with no cheats, no unlocks, no metals, no high scores, no names, no friends, no survey boxes, no diy 101/job center, no diy studio, no traces, absolutely nothing but injected microgames) for doujinsoft.

**Comment by Difegue** [comment]
👋 I'm not really sure what this issue is about in the end, but I don't think it's that useful to host game saves in Doujinsoft (gamefaqs does it well enough and has been around way longer than I am) so I don't plan on doing that.

...Are you making a new account and deleting it after each comment?

**Comment by hutesylvaino** [comment]
[WarioWare D.I.Y. clean no cheats fresh micros saves - quick port from the GameFaqs D.I.Y. Showcase saves (Rev 1).zip](https://github.com/Difegue/DoujinSoft/files/9568465/WarioWare.D.I.Y.clean.no.cheats.fresh.micros.saves.-.quick.port.from.the.GameFaqs.D.I.Y.Showcase.saves.Rev.1.zip)
this save is not to upload it to DoujinSoft as you mentioned, this is a updated revision of that last zip, as the last zip had the slot 3 micros in "All Theme 3 (Creatures) contest winner microgames" and "All Themes 11, 12 and 13 Cute (Shelf 1) Winter (Shelf 2) and Masterpiece (shelves 3 and 4)" that are in the gamefaqs save accidently missing in the ds version, out of blindness, dehydrated, ocd, and being anxious. warning now avoid that august 25, 2022 upload, this is a much better version, it even has real hardware sav support.

the reason why i delete the account is just to remain anonymous, not called out by any username, and not be credited,

**Comment by hutesylvaino** [comment]
it's time to delete this nonsense of a issue, if the openemu github page can delete issues, so can this page delete this issue too.
